/**
 * The type of Item. The types can be: MISC, AMULET, BOOTS, BRACERS, CHEST,
 * GLOVES, GOGGLES, HAT, MELEE_WEAPON, PANTS, RING, SHIELD, SHOULDER, SOCKS,
 * BELT, EARRING;}
 */

public enum ItemType {
	MISC, AMULET, BOOTS, BRACERS, CHEST, GLOVES, GOGGLES, HAT, MELEE_WEAPON, PANTS, RING, SHIELD, SHOULDER, SOCKS, BELT, EARRING;
}